---
title: "DMII"
author: "Ana Catarina Monteiro, Artur Ferreira, Lucas Parada"
date: "4/25/2020"
output: html_document


---

```{r setup, include=FALSE}
#libraries  
library(dplyr)
library(ggplot2)

```


```{r setup, include=FALSE}
  
movies <- read.csv('data/movies.csv')
profiles <- read.csv('data/profiles.csv')
#ratings <- read.csv('data/ratings.csv')  


```

```{r setup, include=FALSE}

profiles['agegroup'] <- profiles['age'] %>% mutate(age = 
                                              ifelse(is.na(age) , "Desconhecido",
                                              ifelse(age >= 10 & age < 18, 'Adolescente',
                                                     ifelse(age >= 18 & age < 65, 'Adulto',
                                                            ifelse(age >= 65, 'Idoso', "Desconhecido")))))


age_raw <- data.frame(
  name = c("Adolescente","Adulto", "Desconhecido", "Idoso"), 
  value = profiles['agegroup'] %>% count(agegroup))

age_raw_plot = ggplot(age_raw, aes(x=name, y=value.n)) + 
  geom_bar(stat = "identity" ,
           fill = c("#33cc33", "#3399ff","#4d4d4d", "#6600ff")) + 
  labs(title="Figura 2: Utilizadores por género",
       x="Sexo", y="Nº de Utilizadores")



```

```{r setup, include=FALSE}





# Create data
gender_raw <- data.frame(
  name = c("Desconhecido","Feminino", "Masculino"), 
  value = profiles['gender'] %>% count(gender))

gender_raw_plot = ggplot(gender_raw, aes(x=name, y=value.n)) + 
  geom_bar(stat = "identity" ,
           fill = c("#4d4d4d", "#ff1ac6", "#0066ff")) + 
  labs(title="Figura 2: Utilizadores por género",
       x="Sexo", y="Nº de Utilizadores")

# Preliminary Analisys

# How many movies exist?
print(length(movies$movieid))

# And how many have ratings?
print(length(unique(ratings$movieid)))

# So, we have that
print(length(movies$movieid) - length(unique(ratings$movieid)))
# movies that are not relevant in this study. 
# Almost a third of the table!
# let's remove those

relevant <- unique(ratings$movieid)

movies <- movies[match(movies$movieid, relevant, nomatch=0),] 

```





```{r setup, include=FALSE}

# Not only do we want movies with ratings, 
# we them to be good ratings , let's say 3
# and with at least some ratings, let's say 10.
ratings['rating'] = floor(ratings$rating)
ratings = filter(ratings, rating >= 3)
positive <- ratings %>% count(movieid)
positive = filter(positive_count, n >= 10)
ratings <- filter(ratings, movieid %in% positive$movieid)
movies <- filter(movies, movieid %in% positive$movieid)


```



```{r setup, include=FALSE}

# Create data
data <- data.frame(
  name = c(3,4,5), value = ratings %>% count(rating)
  )
# Barplot
ggplot(data, aes(x=factor(name), y=value.n)) + 
  geom_bar(stat = "identity" ,
           fill = c( "#fefe01", "#bffe01", "#80fe01")) + 
  theme(legend.position="none") +
    labs(
    title="Figura 1: Ratings de filmes com mais de 10 ratings \"positivos\"",
       x="Rating",
       y="Nº of ratings")
```


```{r setup, include=FALSE}

users_prof <- unique(profiles$userid)
c_users_prof <- length(users_prof)
# Number of total users
print(c_users_prof)


users_rat <- unique(ratings$userid)
c_users_rat <- length(users_rat)
# Number of users that have rated a movie
print(c_users_rat)


# Number of useless users
print(c_users_prof - c_users_rat)

profiles <- filter(profiles, userid %in% users_rat)

```


```{r setup, include=FALSE}

# Create data
gender_pro <- data.frame(
  name = c("Desconhecido","Feminino", "Masculino"), value = profiles['gender'] %>% count(gender)
  )
# Barplot
gender_pro_plot = ggplot(gender_pro, aes(x=name, y=value.n)) + 
  geom_bar(stat = "identity" ,
           fill = c("#4d4d4d", "#ff1ac6", "#0066ff")) + 
  labs(title="Figura 2: Utilizadores que já classificaram um filme por género",
       x="Sexo", y="Nº de Utilizadores") 

grid.arrange(gender_raw_plot, gender_pro_plot, ncol=2)

```


```{r setup, include=True}

age_pro <- data.frame(
  name = c("Adolescente","Adulto", "Desconhecido", "Idoso"), 
  value = profiles['agegroup'] %>% count(agegroup))

age_pro_plot = ggplot(age_pro, aes(x=name, y=value.n)) + 
  geom_bar(stat = "identity" ,
           fill = c("#33cc33", "#3399ff","#4d4d4d", "#6600ff")) + 
  labs(title="Figura 2: Utilizadores por género",
       x="Sexo", y="Nº de Utilizadores")

grid.arrange(age_raw_plot, age_pro_plot, ncol=2)

age_pro_plot
```

